### ISSUE TITLE
What are Imagemagick's legacy tools?

### ISSUE THREAD

**Issue by Gemdation** [ftde0/yt2009#103]
Installation was going well until I realized there is an issue that is happening with imagemagick. I have it installed, but it says it isn't found. I then noticed that the readme says to install it's legacy tools, how exactly would I get that on Linux Mint?
>- **make sure you have [imagemagick](https://imagemagick.org/) and [ffmpeg](https://ffmpeg.org/) in your PATH.**
>### when installing imagemagick, make sure you also install its legacy tools (convert)! 
```node post_config_setup.js
== checking external tool: ffmpeg
== checking external tool: magick
magick not found!! make sure it is in your path
exiting

**Comment by gohoski** [comment]
In order to get them, I had to [build imagemagick from source](https://itsfoss.com/install-imagemagick-ubuntu/#install-latest-version-of-imagemagick-from-the-source-code-for-advanced-and-desperate-users-). Please correct me if I'm wrong and it is possible to get them prebuilt.

Don't forget to `sudo apt purge imagemagick* -y` before building it.

**Comment by Gemdation** [comment]
I forgot to reply to this but thanks, building from source did let me get past that.
