### ISSUE TITLE
Just edited the signin.htm file to no longer have the "Shows" button

### ISSUE THREAD

**Issue by gigigigi53** [ftde0/yt2009#124]
[signin.zip](https://github.com/user-attachments/files/16673778/signin.zip)
You could update it into your yt2009 code! thank you!

**Comment by mrkrabs206** [comment]
Also rename from subtitle-module.swf to subtitle_module.swf

**Comment by gigigigi53** [comment]
> the "shows" button was there in the sign in page in 2009, which is why it's in yt2009 as well. http://web.archive.org/web/20091027180240/https://www.google.com/accounts/ServiceLogin?uilel=3&service=youtube&passive=true&continue=http%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26nomobiletemp%3D1%26hl%3Den_US%26next%3D%252F&hl=en_US&ltmpl=sso what's the point in removing it?

Idk bro since it was gone in all pages, i also decided to remove it on sign in :/

**Comment by gigigigi53** [comment]
Also read my last comment on issue #122

**Comment by ftde0** [comment]
the shows button is a different story. it can be enabled with the `shows_tab` global flag, which will make it show on all pages.
what IS true (and shouldn't have happened) is that the sign in page doesn't respect that setting and shows it all the time. that will be fixed.

refering to #122:
- due to limitations of those mobile apps, in order to bring every possible feature i'd need to make separate requests for each video, around 20 per feed (search, homepage, related videos etc). this would noticeably slow down loading times.
- also, as mentioned in #106, i don't have the setup to test all early apks, so research in getting those working is not really a possibility for me as of now.
- i've tried escargot before under a different name. as cool as the novelty is, having to keep it on the taskbar at all times when i'm available for the client to work isn't really something that's convenient. i'd rather stick to this github issue tracker for yt2009-related things.

**Comment by mrkrabs206** [comment]
> the shows button is a different story. it can be enabled with the `shows_tab` global flag, which will make it show on all pages. what IS true (and shouldn't have happened) is that the sign in page doesn't respect that setting and shows it all the time. that will be fixed.
> 
> refering to #122:
> 
> * due to limitations of those mobile apps, in order to bring every possible feature i'd need to make separate requests for each video, around 20 per feed (search, homepage, related videos etc). this would noticeably slow down loading times.
> * also, as mentioned in [Implement `/proxy/` requests for YouTube 1.4.20 support #106](https://github.com/ftde0/yt2009/issues/106), i don't have the setup to test all early apks, so research in getting those working is not really a possibility for me as of now.
> * i've tried escargot before under a different name. as cool as the novelty is, having to keep it on the taskbar at all times when i'm available for the client to work isn't really something that's convenient. i'd rather stick to this github issue tracker for yt2009-related things.

But what about captions on mobile apps

**Comment by ftde0** [comment]
addressed in https://github.com/ftde0/yt2009/commit/b6c48749c7f0197ac165ff1a1dd003560a304221
