### ISSUE TITLE
ytsession error after i put the code

### ISSUE THREAD

**Issue by SuperLuigiKillz04** [ftde0/yt2009#161]
also the recommended for you tab disappears when i get in to the instance

i followed the instructions that were shown in the logs, but i still get the ytsession error

**Comment by ftde0** [comment]
are you up to date? latest commit is https://github.com/ftde0/yt2009/commit/89a69c87d4dac3427c542ae937ae006c5223c151, you can use `git log` within your yt2009 dir to check.

**Comment by ftde0** [comment]
assuming the account test goes correctly (you see the "account used: \<name\>" line when starting yt2009 - that means it's working)

can you edit `yt2009html.js` before those lines:
```js
if(r.streamingData) {
    yt2009exports.extendWrite("players", id, r)
}
for(let i in r) {
    combinedResponse[i] = r[i]
}
```
(should be after `}).then(r => {r.json().then(r => {`)

to include this piece of code?
```js
fs.writeFileSync("test.json", JSON.stringify(r));
```

---

should make something like this:
```js
fs.writeFileSync("test.json", JSON.stringify(r));
if(r.streamingData) {
    yt2009exports.extendWrite("players", id, r)
}
for(let i in r) {
    combinedResponse[i] = r[i]
}
```



this should create a `test.json` file inside of `back/` containing the response so we can further see what's going on. please remove your identifying data (`datasyncId`s, your IP if it could come up, stuff like that) and send the file here.

---

alternatively, you can include this instead instead of `fs.writeFileSync`...
```js
console.log(r)
```
this will log the needed info to your console stdout. if you go this route, please send the screenshot of what it says.

---

alternatively, if you can't do any of those, use a proxy to get the `/player` request and send its response here.

**Comment by SuperLuigiKillz04** [comment]
![image](https://github.com/user-attachments/assets/4b014270-aafe-4ef9-ac15-50e9f39e088a)
like this?

**Comment by ftde0** [comment]
like that. i've noticed the issue on my end as well though, so if you get a `'Request contains an invalid argument.',` message, it's known by now. a fix should be out by next week.

**Comment by SuperLuigiKillz04** [comment]
thx

**Comment by ftde0** [comment]
fixed in https://github.com/ftde0/yt2009/commit/70d5735ae6e1f3e3dda0ab4299ac06ccd01c719d

**Comment by SuperLuigiKillz04** [comment]
where do i put the token?

hosting this on render

**Comment by breakgimme** [comment]
sorry for taking longer than promised, i added a workaround in 17c4966a31ca2961b156860dd7662c9ac5486b5c
@SuperLuigiKillz04 can you test if it works so i can close the issue?

**Comment by SuperLuigiKillz04** [comment]
it works, but the recommended for you tab still disappears
