### ISSUE TITLE
Earlier versions of YouTube do not work with YT2009.

### ISSUE THREAD

**Issue by mrkrabs206** [ftde0/yt2009#67]
They did their best, but they have problems with it.
Is there a reason why?

**Comment by ftde0** [comment]
1.6.21 and below are way more involved when it comes to getting those to work. mainly:
- 1.6.20 and below don't work on modern Android AT ALL due to those relying on APIs that are long gone,
- 1.6.21 has obfuscated class names when decompiled (2.x don't), making them harder to work with
- they check whether the device has an IMEI number and crash otherwise. this check ideally needs to be patched out
- they have a shouldUseMASF check that determines whether protobuf (/mobilevideo, unimplemented and unsure whether possible) or gdata (implemented and used by apps). this check also should be patched out to not use /mobilevideo
- /registerDevice calls are more strict
- some feed requests have only been used in those 1.6.21> apps and would most likely need to be changed up/reimplemented to fully work.

not to say getting those apps isn't impossible but those bullet points above are only on top of what's normally needed to redirect apps to use yt2009.

**Comment by mrkrabs206** [comment]
> 1.6.21 and below are way more involved when it comes to getting those to work. mainly:
> 
> * 1.6.20 and below don't work on modern Android AT ALL due to those relying on APIs that are long gone,
> * 1.6.21 has obfuscated class names when decompiled (2.x don't), making them harder to work with
> * they check whether the device has an IMEI number and crash otherwise. this check ideally needs to be patched out
> * they have a shouldUseMASF check that determines whether protobuf (/mobilevideo, unimplemented and unsure whether possible) or gdata (implemented and used by apps). this check also should be patched out to not use /mobilevideo
> * /registerDevice calls are more strict
> * some feed requests have only been used in those 1.6.21> apps and would most likely need to be changed up/reimplemented to fully work.
> * instances MUST be on port 80. it's not a matter of "optional" and "can be worked around with a redirect". requests can't be redirected or they will fail.
> 
> not to say getting those apps isn't impossible but those bullet points above are only on top of what's normally needed to redirect apps to use yt2009.

If you have time, make tutorial of YT2009 apk setup (apk_setup_earlyvers.md).
